name: Build and Package WebExtension Assets

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_assets:
    runs-on: ubuntu-latest

    env:
      WEBEXTENSION_DIR: ./webextension

    outputs:
      webextension_dir: ${{ env.WEBEXTENSION_DIR }}
      dist_chrome_dir: ${{ env.WEBEXTENSION_DIR }}/dist-chrome
      dist_firefox_dir: ${{ env.WEBEXTENSION_DIR }}/dist-firefox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install GJS (GNOME JavaScript)
        run: sudo apt update && sudo apt install -y gjs

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WEBEXTENSION_DIR }}

      - name: Run Build Scripts (pack)
        run: npm run pack
        working-directory: ${{ env.WEBEXTENSION_DIR }}

      # Upload the pre-created ZIPs as assets
      - name: Upload Chrome ZIP Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.WEBEXTENSION_DIR }}/gsconnect-chrome.zip
          asset_name: gsconnect-chrome-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox ZIP Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.WEBEXTENSION_DIR }}/gsconnect-firefox.zip
          asset_name: gsconnect-firefox-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

  # ----------------------------------------------------------------------
  # JOB 2: Create and Upload CRX (Chrome)
  # ----------------------------------------------------------------------
  create_crx:
    needs: build_assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create CRX file
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          extensionDir: ${{ needs.build_assets.outputs.dist_chrome_dir }}
          crxFilePath: gsconnect-chrome.crx
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload CRX Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: gsconnect-chrome.crx
          asset_name: gsconnect-chrome-${{ github.event.release.tag_name }}.crx
          asset_content_type: application/x-chrome-extension

  # ----------------------------------------------------------------------
  # JOB 3: Create and Upload XPI (Firefox)
  # ----------------------------------------------------------------------
  create_xpi:
    needs: build_assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create XPI file
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ${{ needs.build_assets.outputs.dist_firefox_dir }}
          artifacts: ./xpi-output

      - name: Upload XPI Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xpi-output/*.xpi
          asset_name: gsconnect-firefox-${{ github.event.release.tag_name }}.xpi
          asset_content_type: application/x-xpinstall
