on:
  push:
    tags:
      - "v[0-9]+.*"
  workflow_dispatch:

name: WebExtension Release

jobs:
  release:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      WEBEXTENSION_DIR: ./webextension
      TAG_VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ${{ env.WEBEXTENSION_DIR }}/package-lock.json

      - name: Install System Dependencies

        run: sudo apt-get update && sudo apt-get install -y gjs

      - name: Install Node Dependencies
        run: npm ci
        working-directory: ${{ env.WEBEXTENSION_DIR }}

      - name: Run Build and Pack Scripts
        run: npm run pack
        working-directory: ${{ env.WEBEXTENSION_DIR }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_VERSION }}
          name: Release ${{ env.TAG_VERSION }}
          draft: false
          prerelease: false

          files: |
            ${{ env.WEBEXTENSION_DIR }}/gsconnect-chrome.zip
            ${{ env.WEBEXTENSION_DIR }}/gsconnect-firefox.zip

      - name: Create CRX file
        id: create_crx
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: ${{ env.WEBEXTENSION_DIR }}/gsconnect-chrome.zip
          crxFilePath: gsconnect-chrome-${{ env.TAG_VERSION }}.crx
          privateKey: ${{ secrets.CRX_PRIVATE_KEY }}

      - name: Upload CRX Asset
        uses: softprops/action-gh-release@v2
        with:
          files: gsconnect-chrome-${{ env.TAG_VERSION }}.crx
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
